CREATE TABLE USERS
(
    ID          SERIAL PRIMARY KEY,
    FIRSTNAME   VARCHAR(100),
    LASTNAME    VARCHAR(100)
);

CREATE TABLE POSTS
(
    ID          SERIAL PRIMARY KEY,
    USER_ID     BIGINT UNSIGNED NOT NULL,
    BODY        VARCHAR(1024),
    FOREIGN KEY (USER_ID) REFERENCES USERS(ID)
);

SELECT * FROM USERS;

INSERT INTO USERS (FIRSTNAME, LASTNAME)
VALUES ("John", "Smith");

COMMIT;

INSERT INTO POSTS (USER_ID, BODY)
VALUES (1, "This is my first post on this forum!");

COMMIT;

SELECT * FROM POSTS;

INSERT INTO USERS (FIRSTNAME, LASTNAME)
VALUES ("Zachary", "Lee");

INSERT INTO USERS (FIRSTNAME, LASTNAME)
VALUES ("Stephanie", "Kovalsky");

INSERT INTO USERS (FIRSTNAME, LASTNAME)
VALUES ("Thomas", "Landgren");

INSERT INTO USERS (FIRSTNAME, LASTNAME)
VALUES ("John", "Thomson");

INSERT INTO POSTS (USER_ID, BODY)
VALUES (2, "This is my first post too!");

INSERT INTO POSTS (USER_ID, BODY)
VALUES (2, "How are you?");

INSERT INTO POSTS (USER_ID, BODY)
VALUES (1, "Quite good, thanks bro!");

INSERT INTO POSTS (USER_ID, BODY)
VALUES (4, "Yo all! Here is Thomas!");

COMMIT;

SELECT ID, LASTNAME FROM USERS;

SELECT ID, FIRSTNAME FROM USERS
WHERE ID >= 3;

SELECT ID, FIRSTNAME, LASTNAME FROM USERS
WHERE (ID >= 4 AND ID <= 10) OR ID = 1;

SELECT COUNT(*) FROM USERS;

SELECT MIN(ID), MAX(ID) FROM USERS;

SELECT SUM(ID) AS TOTAL, AVG(ID) AS AVERAGE FROM USERS;

SELECT U.FIRSTNAME, U.LASTNAME, P.BODY
FROM USERS U 
JOIN POSTS P ON U.ID = P.USER_ID;
    
SELECT USER_ID, COUNT(*) AS POSTS_NUMBER
FROM POSTS
GROUP BY USER_ID;

SELECT USER_ID, COUNT(*) AS POSTS_NUMBER
FROM POSTS
GROUP BY USER_ID
HAVING COUNT(*) > 1;

SELECT U.FIRSTNAME, U.LASTNAME, COUNT(*) AS POSTS_NUMBER
FROM USERS U
JOIN POSTS P ON U.ID = P.USER_ID
GROUP BY P.USER_ID
HAVING COUNT(*) > 1;

SELECT U.FIRSTNAME, U.LASTNAME, COUNT(*) AS POSTS_NUMBER
FROM USERS U
JOIN POSTS P ON U.ID = P.USER_ID
GROUP BY P.USER_ID
HAVING COUNT(*) > 1
ORDER BY U.LASTNAME, U.FIRSTNAME;

UPDATE POSTS
SET USER_ID = 3
WHERE ID = 4;

COMMIT;

SELECT * FROM POSTS;

DELETE FROM POSTS
 WHERE ID = 4;

COMMIT;
