SELECT 
    I.DESCRIPTION, j.NAME
FROM
    issues I
        JOIN
    issueslists j ON I.ISSUESLIST_ID = j.id;

SELECT 
    I.DESCRIPTION, U.FIRSTNAME, U.LASTNAME
FROM
    issues I
        JOIN
    users U ON I.USER_ID_ASSIGNEDTO = U.id;

SELECT 
    U.FIRSTNAME, U.LASTNAME, COUNT(*) AS DESCRIPTION_NUMBER
FROM
    USERS U
        JOIN
    issues I ON U.ID = I.USER_ID_ASSIGNEDTO
GROUP BY I.USER_ID_ASSIGNEDTO
HAVING COUNT(*) >= 1
ORDER BY U.LASTNAME , U.FIRSTNAME;